name: Java Review

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1

      # CHECKSTYLE
      - name: Run Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.4/checkstyle-10.12.4-all.jar
          java -jar checkstyle-10.12.4-all.jar -c .github/checkstyle.xml -f xml . > checkstyle-result.xml || true

      - name: Reviewdog Checkstyle
        run: |
          cat checkstyle-result.xml | reviewdog -f=checkstyle -reporter=github-pr-review -level=warning
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}